---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: "pr-devops-toolkit\r-1\r\r"
  namespace: argocd
spec:
  destination:
    namespace: "pr-devops-toolkit\r-1\r\r"
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: "image:\n  tag: \"2.6.2\r\"\ningress:\n  host: \"pr-devops-toolkit\r-1\r\r..xip.io\"\n"
      version: v3
    path: helm
    repoURL: "https://github.com/systemdevformations/devops-toolkit\r.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
